// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH1Y-HgFs5I-zw9QSkIt-lfklmquYTiHg',
    appId: '1:120073706521:web:41cfbccead9fdcd1de5e88',
    messagingSenderId: '120073706521',
    projectId: 'movies-api-b8c82',
    authDomain: 'movies-api-b8c82.firebaseapp.com',
    storageBucket: 'movies-api-b8c82.appspot.com',
    measurementId: 'G-K1PFR9GXLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU3KX_HPxD3x1Mo0nLrtq4_v27f7HnteA',
    appId: '1:120073706521:android:cc8d9c7520e202d5de5e88',
    messagingSenderId: '120073706521',
    projectId: 'movies-api-b8c82',
    storageBucket: 'movies-api-b8c82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqbdLwJSd5ngkd0qZOq0ZfB2y2v9R_r9k',
    appId: '1:120073706521:ios:49d75bda3784ce68de5e88',
    messagingSenderId: '120073706521',
    projectId: 'movies-api-b8c82',
    storageBucket: 'movies-api-b8c82.appspot.com',
    iosClientId: '120073706521-4ij355o8v371jvgbmru7o1lii0npn2tl.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqbdLwJSd5ngkd0qZOq0ZfB2y2v9R_r9k',
    appId: '1:120073706521:ios:49d75bda3784ce68de5e88',
    messagingSenderId: '120073706521',
    projectId: 'movies-api-b8c82',
    storageBucket: 'movies-api-b8c82.appspot.com',
    iosClientId: '120073706521-4ij355o8v371jvgbmru7o1lii0npn2tl.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApi',
  );
}
